### ISSUE TITLE
Inferno is in development mode

### ISSUE THREAD

**Issue by Havunen** [Monadical-SAS/inferno-redux-time#1]
Hi,

Inferno is running in development mode. Development mode is used to help devs during development workflow, it has additional validations and other helper runtime functionality. Production mode is optimized for the speed, when benchmarking production build (`process.env.NODE_ENV === "production"`)+ minified code should be used. Inferno 5.3.0 logs a warning to console when development mode is used.

**Comment by yamijuan** [comment]
closed by #2
